title = "I'm Kevin Adrian Pillay"
author = "Kevin Adrian Pillay"
#copyright = "2020-2021"
description = """
The homepage of Kevin Adrian Pillay
System Administrator, Cybersecurity Profesional and Developer
"""
profilePicture = "images/profile.webp"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# fullPostContent = true
contentratio = 0.8

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

[simpleAnalytics]
# enable = true
# customurl = "https://kevinadrian.dev"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[socialIcons]]
icon = "fab fa-linkedin-in"
title = "Linkedin"
url = "https://www.linkedin.com/in/kevinadrianpl/"

[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/kevinadrianpl/"

[[socialIcons]]
icon = "fab fa-github-alt"
title = "GitHub"
url = "https://github.com/kevinadrianpl/"

[[socialIcons]]
icon = "fas fa-user-secret"
title = "TryHackMe"
url = "https://tryhackme.com/p/kevinadrianpl"

[[socialIcons]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:kevin@kevinadrian.dev"
